# Generated by Django 5.2.11 on 2026-02-24 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('electricity_kwh', models.FloatField(default=0.0)),
                ('water_m3', models.FloatField(default=0.0)),
                ('gas_kwh', models.FloatField(default=0.0)),
                ('cost_eur', models.FloatField(default=0.0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='energy.home')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['home', 'timestamp'], name='energy_read_home_id_4239cd_idx')],
            },
        ),
    ]
