# Generated by Django 5.2.11 on 2026-05-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_start', models.DateTimeField()),
                ('total_predicted_kwh', models.FloatField()),
                ('estimated_cost_eur', models.FloatField(blank=True, null=True)),
                ('recommended_tariff', models.CharField(blank=True, max_length=120, null=True)),
                ('hourly_data', models.JSONField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='energy.home')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
