# Generated by Django 5.2.11 on 2026-05-06 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_predictionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH_NIGHT_USAGE', 'Consumo nocturno inusualmente alto'), ('ANOMALOUS_PEAK', 'Pico de consumo anómalo'), ('HIGH_STANDBY', 'Consumo base elevado sostenido'), ('TARIFF_SAVING', 'Posible ahorro por cambio de tarifa')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('start_period', models.DateTimeField(blank=True, null=True)),
                ('end_period', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('RESOLVED', 'Resuelta'), ('DISMISSED', 'Descartada')], default='ACTIVE', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('observed_value', models.FloatField(blank=True, null=True)),
                ('reference_value', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='energy.home')),
            ],
            options={
                'ordering': ['-detection_date'],
                'indexes': [models.Index(fields=['home', 'status', 'alert_type'], name='energy_aler_home_id_1d75af_idx')],
            },
        ),
    ]
