# Generated by Django 5.2.11 on 2026-05-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('HIGH_NIGHT_USAGE', 'Consumo nocturno inusualmente alto'), ('ANOMALOUS_PEAK', 'Pico de consumo anómalo'), ('HIGH_STANDBY', 'Consumo base elevado sostenido'), ('TARIFF_SAVING', 'Posible ahorro por cambio de tarifa'), ('HIGH_USAGE', 'Consumo semanal inusualmente alto')], max_length=50),
        ),
    ]
