# Generated by Django 5.2.11 on 2026-06-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('HIGH_NIGHT_USAGE', 'Consumo nocturno inusualmente alto'), ('ANOMALOUS_PEAK', 'Pico de consumo anómalo'), ('HIGH_STANDBY', 'Consumo base elevado sostenido'), ('TARIFF_SAVING', 'Posible ahorro por cambio de tarifa'), ('HIGH_USAGE', 'Consumo semanal inusualmente alto'), ('COMMUNITY_COMPARE', 'Comparativa con vecinos')], max_length=50),
        ),
    ]
