# Generated by Django 5.2.11 on 2026-06-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_alter_alert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffRecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('home', 'timestamp'), name='unique_home_reading_timestamp'),
        ),
        migrations.AddField(
            model_name='tariffrecommendationresult',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_result', to='energy.home'),
        ),
    ]
