# Generated by Django 5.2.11 on 2026-05-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_power_p1',
            field=models.FloatField(default=3.45),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_power_p2',
            field=models.FloatField(default=3.45),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_tariff_fixed_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_tariff_p1_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_tariff_p2_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_tariff_p3_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_tariff_type',
            field=models.CharField(choices=[('PVPC', 'PVPC (Mercado Regulado)'), ('FIXED', 'Libre Fijo (Precio único)'), ('TOU', 'Libre 3 Periodos (Discriminación Horaria)')], default='PVPC', max_length=10),
        ),
    ]
